### ISSUE TITLE
Здравие вам 

### ISSUE THREAD

**Issue by Anar0x19** [thisisignitedoreo/ccommons#1]
Я заметил некоторые недоработки вашего кода связанными в основном в работе с памятью: 

1. Утечка памяти: Функции b64_encode_alphabet, b64_decode_alphabet и другие выделяют память с помощью malloc, но никогда не освобождают её. Это приведет к утечкам памяти, если вызовы функций будут повторяться. вызывающий код должен заботиться о освобождении памяти, или можно использовать статическую область памяти (но это менее гибко).
2. Функция strnlen работает не во всех стандартах C Это может ограничить переносимость кода. Более стандартный способ – использовать strlen с проверкой переполнения.
3. Для чисел 64,65 которые часто встречаются в коде лучше использовать именованные константы для читабельности)
4. Также вы избыточно вызываете strlen в функции _b64_string_pos и _b64_count на каждой итерации, что неоптимально, так как строка не меняет свою длину. Лучше один раз вычислить длину строки и сохранить её в переменной.

**Comment by thisisignitedoreo** [comment]
спасибо за заметки, постараюсь исправить. и да, строки после использования надо freeить руками

**Comment by thisisignitedoreo** [comment]
по большей части критические ошибки исправил в последнем коммите, но в функциях _b64_string_pos и _b64_count уже длина была в переменной, не знаю с чего вы взяли что она strlen вызывается на каждой итерации. и я не вижу смысла использовать именованые константы для 3 раз число 65 было использовано.
